# site settings
title: GODSON OSELE
subtitle:
email: obum@stanford.edu
description: A website dedicated to chronicling the work and passion projects of Obumneme Godson Osele
baseurl:  # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Godson Osele
street_address:
city: Stanford
state: CA
zip_code: 94305
country: United States of America
# phone: (470) 435-1425

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 8

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/g-osel
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: https://www.linkedin.com/in/godson-osele
  Twitter:
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md
